# nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: boat-bay-frontend
    description: Backend for Boat bay which lints, compare openapi specs
    annotations:
        slack/conversation-id: C01EQ60LXK8
    tags:
        - openapi
        - angular
        - boat
    links:
        - url: 'https://github.com/Backbase/boat-bay/actions/workflows/boat-ui-release.yml'
          title: Frontend Release
          icon: cloud
        - url: 'https://github.com/Backbase/boat-bay/actions/workflows/boat-ui-pr.yml'
          title: Frontend PR build
          icon: cloud
spec:
    type: tool
    lifecycle: experimental
    owner: de/backend-foundation
