/**
 * Boat Bay Dashboard Server API
 * Endpoints for the boat bay operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */

import { IntRange } from './intRange';
import { Severity } from './severity';
import { BoatLintRule } from './boatLintRule';


export interface BoatViolation { 
    ["rule"]: BoatLintRule;
    ["description"]: string;
    ["severity"]: Severity;
    ["lines"]: IntRange;
    ["pointer"]: string;
}

