/**
 * Boat Bay Dashboard Server API
 * Endpoints for the boat bay operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */

import { Changes } from './changes';
import { BoatCapability } from './boatCapability';
import { BoatService } from './boatService';
import { BoatStatistics } from './boatStatistics';


export interface BoatSpec { 
    ["id"]: number;
    ["key"]: string;
    ["name"]: string;
    ["title"]?: string;
    ["description"]?: string;
    ["icon"]?: string;
    ["version"]: string;
    ["grade"]?: string;
    ["createdOn"]?: string;
    ["createdBy"]?: string;
    ["statistics"]?: BoatStatistics;
    ["backwardsCompatible"]?: boolean;
    ["changes"]?: Changes;
    ["capability"]: BoatCapability;
    ["serviceDefinition"]: BoatService;
    ["openApi"]?: string;
}

