/**
 * Boat Bay Dashboard Server API
 * Endpoints for the boat bay operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



export type Changes = 'INVALID_VERSION' | 'NOT_APPLICABLE' | 'ERROR_COMPARING' | 'UNCHANGED' | 'COMPATIBLE' | 'BREAKING';

export const Changes = {
    INVALIDVERSION: 'INVALID_VERSION' as Changes,
    NOTAPPLICABLE: 'NOT_APPLICABLE' as Changes,
    ERRORCOMPARING: 'ERROR_COMPARING' as Changes,
    UNCHANGED: 'UNCHANGED' as Changes,
    COMPATIBLE: 'COMPATIBLE' as Changes,
    BREAKING: 'BREAKING' as Changes
};

