/**
 * Boat Bay Dashboard Server API
 * Endpoints for the boat bay operations
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */



export type Severity = 'MUST' | 'SHOULD' | 'MAY' | 'HINT';

export const Severity = {
    MUST: 'MUST' as Severity,
    SHOULD: 'SHOULD' as Severity,
    MAY: 'MAY' as Severity,
    HINT: 'HINT' as Severity
};

