# nonk8s
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: boat-bay-server
    description: Backend for Boat bay which lints, compare openapi specs
    annotations:
        jira/maint-component: API Toolkit
        jira/maint-subcomponent: BOAT
        jira/project-key: DAS
        slack/conversation-id: C02UMAFHFAB
    tags:
        - openapi
        - java
        - boat-bay
    links:
        - url: 'https://github.com/Backbase/boat-bay/actions/workflows/boat-server-release.yml'
          title: Backend Release
          icon: dashboard
        - url: 'https://github.com/Backbase/boat-bay/actions/workflows/boat-server-pr.yml'
          title: Backend PR build
          icon: dashboard
        - url: 'https://github.com/Backbase/boat-bay/pkgs/container/boat-bay'
          title: Docker Image
          icon: dashboard
        - url: 'https://boatbay.backbase.eu/'
          title: Main Deployment
          icon: dashboard
        - url: 'https://github.com/backbase-rnd-cloudops/rnd-gitops/tree/master/clusters/cicd-services/boatbay'
          title: Main Deployment Pipeline
          icon: dashboard
spec:
    type: internal
    lifecycle: experimental
    owner: DE - API Sandbox
