openapi: 3.0.0
info:
  title: Boat Bay Project RegisterAPI
  description: API used for Project Registration
  license:
    name: Backbase
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: register
paths:
  /api/boat/register/project:
    post:
      tags:
        - register
      summary: Register new Project
      description: Creates a new Boat Bay Portal with convention based configuration for setting up a capability team.
      operationId: registerProject
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterProject"
      responses:
        201:
          description: Returns success
        400:
          description: "Failed to register project"

components:
  schemas:
    RegisterProject:
      type: object
      properties:
        key:
          type: string
          description: "The project key used to be used in URLs"
        name:
          type: string
        bom:
          $ref: "#/components/schemas/Bom"
    Bom:
      type: object
      description: "Bill Of Materials used to identify released versions"
      properties:
        groupId:
          type: string
          description: "Maven Group ID"
        artifactId:
          type: string
          description: "Maven Artifact Id"
        versionRange:
          type: string
          description: "Maven Version Range"
        specArtifactFilter:
          type: string
          default: "*:*:*:api:*"



