name: Frontend Release

#on.push.paths will trigger on every push, even in PR's
on:
  push:
    branches:
      - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'boat-bay-frontend/**'

  # JOB to release frontend
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

#          npm version minor # To automatically increase the minor version, will have to push the file as well.
      - name: Prepare variables
        id: vars
        run: |
          cd boat-bay-frontend
          DOCKER_IMAGE=ghcr.io/backbase/boatbay-ui
          DOCKER_TAG=$(node -pe "require('./package.json').version")
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=tag::${DOCKER_TAG}

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin

      - name: Build and Release Image
        run: |
          cd boat-bay-frontend
          npm i
          npm run build-prod
          docker build . --file Dockerfile --tag ${{steps.vars.outputs.image}}:${{steps.vars.outputs.tag}}
          docker push ${{steps.vars.outputs.image}}:${{steps.vars.outputs.tag}}
